<<<<<<< HEAD
sonar.projectKey=home-essentials-market
sonar.organization=your-org-name

# Tell SonarCloud where to look for your code
sonar.sources=backend,frontend
sonar.python.version=3
sonar.exclusions=**/venv/**, **/node_modules/**
=======
sonar.projectKey=AbuEbunoluwa_catfish-shop
sonar.organization=abuebunoluwa
sonar.sources=.
sonar.language=py
sonar.python.version=3.12.3
>>>>>>> c7f617e (Add sonar project properties)
